package ru.lisss79.weatherforecast.entities

// Ключи временной зоны
const val AUTO = "auto"
const val TIMEZONE = "timezone"
const val UTC_OFFSET_SECONDS = "utc_offset_seconds"

// Основные ключи ответа текущей или прогноза погоды
const val CURRENT = "current"
const val HOURLY = "hourly"

// Ключи параметров погоды
const val APPARENT_TEMPERATURE = "apparent_temperature"
const val APPARENT_TEMPERATURE_MAX = "apparent_temperature_max"
const val APPARENT_TEMPERATURE_MIN = "apparent_temperature_min"
const val CLOUD_COVER = "cloud_cover"
const val DAILY = "daily"
const val HUMIDITY = "relative_humidity_2m"
const val INTERVAL = "interval"
const val IS_DAY = "is_day"
const val PRECIPITATION = "precipitation"
const val PRECIPITATION_PROBABILITY = "precipitation_probability_mean"
const val PRECIPITATION_SUM = "precipitation_sum"
const val RAIN = "rain"
const val RAIN_SUM = "rain_sum"
const val SHOWERS = "showers"
const val SHOWERS_SUM = "showers_sum"
const val SNOWFALL = "snowfall"
const val SNOWFALL_SUM = "snowfall_sum"
const val SURFACE_PRESSURE = "surface_pressure"
const val SUNRISE = "sunrise"
const val SUNSET = "sunset"
const val TEMPERATURE = "temperature_2m"
const val TEMPERATURE_MAX = "temperature_2m_max"
const val TEMPERATURE_MIN = "temperature_2m_min"
const val TIME = "time"
const val WEATHER_CODE = "weather_code"
const val WIND_DIRECTION = "wind_direction_10m"
const val WIND_DIRECTION_DOMINANT = "wind_direction_10m_dominant"
const val WIND_GUSTS_MAX = "wind_gusts_10m_max"
const val WIND_SPEED = "wind_speed_10m"
const val WIND_SPEED_MAX = "wind_speed_10m_max"